language: ruby
services:
  - postgresql
env:
  - START_SIMPLECOV=1
addons:
  postgresql: '9.6'
  code_climate:
    repo_token:
      secure: "fuOaqrrk3fszN5Hdr/GhO8x0H6K9v8e327bUNqB70pCNnvvQViZI8hSycUNkPGKMT/PNNOHItQB9Y8un9ArIZtKO99D2jNmFX9si0j3Z2nmg9BClqM02W6voJKKiEgFyt57JrgWCCxpYHhKcBVJmdcN/yOaxKmnC02LUuZHXfn9PZc+2cwh16Qhzn24vOEwTw7QKro0tYr5qakRd+u9SYVKx+FvYUbksFaQqIYG+2pv53w4blCRz6iuKdH5R/QdpRZU7LajNZT4ijAxrkaoBqRjVh/d7haboqtv9dFi6nFd8ORP9u884nusZG1q3z/DvA6lqnH/hYL5GbM2lH6MzeZUXpKodONcl2EuLHX8TPm4ESrPWOK1OqyHeDG64G/FJUsQFyrLVEmPcnxpb0DhJSx0+faWAVmUAN65/uuVOTAdsRrkTFqGzwNe6NPFw+2F0rWdmIadYBLOPfKkUFmse8tmtxFKn8yUwIO50gqg3bEImY857jqlr/JCtR+/4np0nl0ksiwWnWoWdW7HixX/nvrUmaV3MD7wmet2WVQNOhGBX+AeNlxiI5G+iKsLL5eIyAZHf2R13kGuO7c+4WsaeKq1WLiFg4CdgLnksUcRkqNIPSuExzpk7fa52zx+yW6v7T8RSPdH2zagOvlrZqwwApit9ZQZ8UTuPe3ifFVe4Nac="
before_script:
  - psql -c 'create database "somleng-rtd_test";' -U postgres
  - psql -U postgres -c "create extension pgcrypto"
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
deploy:
  provider: heroku
  api_key:
    secure: MFPbi03N9H90CL/UX9DeXvBurNj1/BnkuYjAq9AaDoDHpIIWozYMEKBzVvhf5kQ29oWT3HPA+6W0iZvOhr/V/nX394bziEssehNEFle2CUDT4bnRrseHEhFIHa8E0dFUm35GaDM5hzTPb/a8JXxTYaK6eekIyJcwD5gow9nmY4v/yHG17Q9Yno2LBBSj8jAX5zDEmkJjU9gkYs+jtZXmNfyi/AA/iCzZWlnOafmLRTggljsixHf9qFAx2eCkigayhvU9ooMK3ecutV6U3bAvqHC+bzSyUXWsMjBJm8Tr9lTOG84lbhTWVvjwrF5JTEp8V+jroBxymZ8Mvmet7MkSdsQzwpS6BGRUHYoeMowJYLIbw5ngMEGiFXW63Zv82u104tQ0wuR2zdj54vZ1OAdKj8+a1IA3hmKqSfwGW4XQFiCdyuO7xe12EPDiZ16GdASFNYjJqy+ctA9WOhaBkr9F6jdmAO2Tb9P9D3oNgPP8juwgUbHXDgYRiWxpUy1nlZv7TpGAWdqHGI5SrjH05xItOuhrsYKzxm12AKjp3tvpZz4zMQEor821azMFuq8TJI4sEkZWlUfagk1grslCRGrCzn6RuoR7AW4aCObdTWSIZVPHSIPfZKdz20hvrQdY665S0aedmMNrynD5qUGmZFYnbUxFqTQZr5/PW0ZydcDXLDY=
  run:
    - "rake db:migrate"
