language: ruby
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database "somleng-rtd_test";' -U postgres
- psql -U postgres -c "create extension pgcrypto"
script:
- bundle exec rake db:schema:load
- bundle exec rake db:test:prepare
deploy:
  provider: heroku
  api_key:
    secure: MFPbi03N9H90CL/UX9DeXvBurNj1/BnkuYjAq9AaDoDHpIIWozYMEKBzVvhf5kQ29oWT3HPA+6W0iZvOhr/V/nX394bziEssehNEFle2CUDT4bnRrseHEhFIHa8E0dFUm35GaDM5hzTPb/a8JXxTYaK6eekIyJcwD5gow9nmY4v/yHG17Q9Yno2LBBSj8jAX5zDEmkJjU9gkYs+jtZXmNfyi/AA/iCzZWlnOafmLRTggljsixHf9qFAx2eCkigayhvU9ooMK3ecutV6U3bAvqHC+bzSyUXWsMjBJm8Tr9lTOG84lbhTWVvjwrF5JTEp8V+jroBxymZ8Mvmet7MkSdsQzwpS6BGRUHYoeMowJYLIbw5ngMEGiFXW63Zv82u104tQ0wuR2zdj54vZ1OAdKj8+a1IA3hmKqSfwGW4XQFiCdyuO7xe12EPDiZ16GdASFNYjJqy+ctA9WOhaBkr9F6jdmAO2Tb9P9D3oNgPP8juwgUbHXDgYRiWxpUy1nlZv7TpGAWdqHGI5SrjH05xItOuhrsYKzxm12AKjp3tvpZz4zMQEor821azMFuq8TJI4sEkZWlUfagk1grslCRGrCzn6RuoR7AW4aCObdTWSIZVPHSIPfZKdz20hvrQdY665S0aedmMNrynD5qUGmZFYnbUxFqTQZr5/PW0ZydcDXLDY=
