# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilreapi_account_sid_encryption_key: <%= ENV["TWILREAPI_ACCOUNT_SID_ENCRYPTION_KEY"] %>
  twilreapi_auth_token_encryption_key: <%= ENV["TWILREAPI_AUTH_TOKEN_ENCRYPTION_KEY"] %>

development: &development
  <<: *production
  secret_key_base: 6e27c4b53fc1f643b24a51311264c35517127ae3f25435d1c994a7a2f77fc84e467546e65dd768d55457b92cae18a78ff63b29fae263bd7eb2425e9e4906ec97
  twilreapi_account_sid_encryption_key: "194cc9fa600fc45060f831b9da4ad1ccb0ae43a8c1d0a6834a41b05245ad173637040f0fbc50c7c49449a7ac010821141a00b50aa7282fae24c961d79dfe36a7"
  twilreapi_auth_token_encryption_key: "7e3a92eb821a5e5b5e82661bc1ff50de04569fb9f71999f7b881299d37b93fad0ef25c2ffc4af42c7931bfcd5840f272290e69b67d41608695f8847681771a78"

test:
  <<: *development
  secret_key_base: cf1a63fce286473c2f83064b0c56981e1ca4d6788580b3af5a96900ae8d8c7964a5d8d731be4e5b85440cfb4a9e7ed1a9d0eac67fddc0f485c22c05dcc98b256

